export const GET_TOKEN='GET_TOKEN';
export const REMOVE_TOKEN='REMOVE_TOKEN';
export const GET_BOOTCAMPS='GET_BOOTCAMPS';
export const GET_BOOTCAMP='GET_BOOTCAMP';
export const GET_BOOTCAMP_ERROR='GET_BOOTCAMP_ERROR';
export const BOOTCAMP_ERROR='BOOTCAMP_ERROR';
export const FILTER_BOOTCAMPS='FILTER_BOOTCAMPS';
export const LOAD_USER='LOAD_USER';
export const LOAD_USER_FAIL='LOAD_USER_FAIL';
export const UPDATE_DETAILS='UPDATE_DETAILS';
export const REQUEST_DENIED='REQUEST_DENIED';
export const SET_ALERT='SET_ALERT';
export const REMOVE_ALERT='REMOVE_ALERT';
export const CLEAR_ERRORS='CLEAR_ERRORS';
export const GET_REVIEWS='GET_REVIEWS'
export const GET_REVIEWS_ERROR='GET_REVIEWS_ERROR'
export const LOGOUT='LOGOUT'


